{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bravepipeproject",
    "module": "timeago-generator",
    "version": "v0.24.8-2.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "timeago-generator-v0.24.8-2.3.4.jar",
          "url": "timeago-generator-v0.24.8-2.3.4.jar",
          "size": 13140,
          "sha512": "ca60168d7908ba6e585348d64dc38ca706395263ee8847a27083dec2bda03cbc4aa1b33a7d8c2c3ec9290d13746bfbed1bcc4fdd0eadeb48be6fd92ca5965462",
          "sha256": "12dd22f276c6759e20f0da8a6600f7b040f0fbab05f6ecb381e30f6480b9cf32",
          "sha1": "293a7ea233a4924adfaccc6599f0ad3257d9b4cb",
          "md5": "05b117d6775c2eae87a54760fd481f76"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.TeamNewPipe",
          "module": "nanojson",
          "version": {
            "requires": "e9d656ddb49a412a5a0a5d5ef20ca7ef09549996"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.github.bravepipeproject",
          "module": "timeago-parser",
          "version": {
            "requires": "v0.24.8-2.3.4"
          }
        }
      ],
      "files": [
        {
          "name": "timeago-generator-v0.24.8-2.3.4.jar",
          "url": "timeago-generator-v0.24.8-2.3.4.jar",
          "size": 13140,
          "sha512": "ca60168d7908ba6e585348d64dc38ca706395263ee8847a27083dec2bda03cbc4aa1b33a7d8c2c3ec9290d13746bfbed1bcc4fdd0eadeb48be6fd92ca5965462",
          "sha256": "12dd22f276c6759e20f0da8a6600f7b040f0fbab05f6ecb381e30f6480b9cf32",
          "sha1": "293a7ea233a4924adfaccc6599f0ad3257d9b4cb",
          "md5": "05b117d6775c2eae87a54760fd481f76"
        }
      ]
    }
  ]
}
