{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bravepipeproject",
    "module": "timeago-generator",
    "version": "v0.24.8-2.3.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "timeago-generator-v0.24.8-2.3.2.jar",
          "url": "timeago-generator-v0.24.8-2.3.2.jar",
          "size": 13011,
          "sha512": "bf55774089198e0cac0a368e87ea92fe67dcdcdfbfde68315c946edbe3e15ce7f2cefcf6bb3425816e137342b50cea021d4eade712b68b863b18e228d8a13151",
          "sha256": "012af08590ba4ef290047cde9c2c6437ba09d43ac6a878c9ddb32c772c942d3a",
          "sha1": "a6e28daa9cdea95b60f34c3aa7b84852052cdbe9",
          "md5": "8f03a1be281098c96091550f426ff053"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.TeamNewPipe",
          "module": "nanojson",
          "version": {
            "requires": "e9d656ddb49a412a5a0a5d5ef20ca7ef09549996"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.github.bravepipeproject",
          "module": "timeago-parser",
          "version": {
            "requires": "v0.24.8-2.3.2"
          }
        }
      ],
      "files": [
        {
          "name": "timeago-generator-v0.24.8-2.3.2.jar",
          "url": "timeago-generator-v0.24.8-2.3.2.jar",
          "size": 13011,
          "sha512": "bf55774089198e0cac0a368e87ea92fe67dcdcdfbfde68315c946edbe3e15ce7f2cefcf6bb3425816e137342b50cea021d4eade712b68b863b18e228d8a13151",
          "sha256": "012af08590ba4ef290047cde9c2c6437ba09d43ac6a878c9ddb32c772c942d3a",
          "sha1": "a6e28daa9cdea95b60f34c3aa7b84852052cdbe9",
          "md5": "8f03a1be281098c96091550f426ff053"
        }
      ]
    }
  ]
}
