{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bravepipeproject",
    "module": "timeago-generator",
    "version": "v0.24.8-2.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "timeago-generator-v0.24.8-2.3.3.jar",
          "url": "timeago-generator-v0.24.8-2.3.3.jar",
          "size": 13011,
          "sha512": "edf4d2406b8b97a343bd41a38d506fce99ed3a73a2627ad4a3b436142032c4be7793d58a57138b16ca152036cb7531eece4146eb0a937a0a6ee79773bb5bf703",
          "sha256": "ac875a442b40acec0b974125ab1756ecb33728fb1b7f05fc829f8e0a08b6935b",
          "sha1": "d2b5c7213f679ee95dbac6b2909d0eae07bb0b74",
          "md5": "c33aa99584ffcd2869f269499cd32f7c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.TeamNewPipe",
          "module": "nanojson",
          "version": {
            "requires": "e9d656ddb49a412a5a0a5d5ef20ca7ef09549996"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.github.bravepipeproject",
          "module": "timeago-parser",
          "version": {
            "requires": "v0.24.8-2.3.3"
          }
        }
      ],
      "files": [
        {
          "name": "timeago-generator-v0.24.8-2.3.3.jar",
          "url": "timeago-generator-v0.24.8-2.3.3.jar",
          "size": 13011,
          "sha512": "edf4d2406b8b97a343bd41a38d506fce99ed3a73a2627ad4a3b436142032c4be7793d58a57138b16ca152036cb7531eece4146eb0a937a0a6ee79773bb5bf703",
          "sha256": "ac875a442b40acec0b974125ab1756ecb33728fb1b7f05fc829f8e0a08b6935b",
          "sha1": "d2b5c7213f679ee95dbac6b2909d0eae07bb0b74",
          "md5": "c33aa99584ffcd2869f269499cd32f7c"
        }
      ]
    }
  ]
}
