{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bravepipeproject",
    "module": "extractor",
    "version": "v0.26.3-2.3.6",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.5.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.wire",
          "module": "wire-runtime",
          "version": {
            "requires": "5.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "extractor-v0.26.3-2.3.6.jar",
          "url": "extractor-v0.26.3-2.3.6.jar",
          "size": 1080818,
          "sha512": "f54a69fb4fa3c60bc33c8bb368c73f1bc737e79c0b06b7f1f45d7ad3536f42623d5560191021a9e1de5934ee9b877cf183b4b28846684620fc5ab00bd3c1b764",
          "sha256": "1ad9a321d30b491b9633a0c7516c4c39051f8b9c4e3a5b3704fe81bfdc4cde61",
          "sha1": "b1e0a5fdecdf4cfefb68a7b34390f68e1c79e4aa",
          "md5": "96989bbafc923de3786700fbb125e17e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.TeamNewPipe",
          "module": "nanojson",
          "version": {
            "requires": "e9d656ddb49a412a5a0a5d5ef20ca7ef09549996"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.22.2"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "4.35.0"
          }
        },
        {
          "group": "org.mozilla",
          "module": "rhino",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.mozilla",
          "module": "rhino-engine",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "com.github.evermind-zz",
          "module": "hlsdownloader",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-runtime",
          "version": {
            "requires": "5.5.0"
          }
        }
      ],
      "files": [
        {
          "name": "extractor-v0.26.3-2.3.6.jar",
          "url": "extractor-v0.26.3-2.3.6.jar",
          "size": 1080818,
          "sha512": "f54a69fb4fa3c60bc33c8bb368c73f1bc737e79c0b06b7f1f45d7ad3536f42623d5560191021a9e1de5934ee9b877cf183b4b28846684620fc5ab00bd3c1b764",
          "sha256": "1ad9a321d30b491b9633a0c7516c4c39051f8b9c4e3a5b3704fe81bfdc4cde61",
          "sha1": "b1e0a5fdecdf4cfefb68a7b34390f68e1c79e4aa",
          "md5": "96989bbafc923de3786700fbb125e17e"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "extractor-v0.26.3-2.3.6-sources.jar",
          "url": "extractor-v0.26.3-2.3.6-sources.jar",
          "size": 656625,
          "sha512": "72d2a70a6801fc2456c9c3eecc2092ae33b712db5c3886145e5eeb9066de41107531c8c796bf7b6b29ca7e8070616b59da1e379d6cde5a2ba4f98bf3c8c33b31",
          "sha256": "19c13fa1dbb0108d395848f0548bdeed08b11a78112099a5a68d0215bf1eaa51",
          "sha1": "47cb7bae227cdd2dc79679634d4962914e898abe",
          "md5": "ab8927d40c25ca8f2abed8990ed8b858"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "extractor-v0.26.3-2.3.6-javadoc.jar",
          "url": "extractor-v0.26.3-2.3.6-javadoc.jar",
          "size": 2609411,
          "sha512": "a1d206269d26d179060beab64c617769be732ebb38d5dac5a348288c52169a93035a82599dff6d6339589640a0af97819ac436751ec45605e03c5233bd544ae4",
          "sha256": "31dedd3520c19fc79bb5e59957954b8cc0a2e06e8efec72aec4bc988fd9dbb7f",
          "sha1": "ff0833a8734705a50431da02f464856c8af53d70",
          "md5": "416de5421afb4d66f69d25bb3f4dc14e"
        }
      ]
    }
  ]
}
