{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bravepipeproject",
    "module": "extractor",
    "version": "v0.24.8-2.3.4",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.wire",
          "module": "wire-runtime",
          "version": {
            "requires": "4.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "extractor-v0.24.8-2.3.4.jar",
          "url": "extractor-v0.24.8-2.3.4.jar",
          "size": 973423,
          "sha512": "22346c82c8d0486b8d2cbfd8a5a4f2e04e01e0a339b9eb73f6af83809cc793f35f75c8156d59b830d5ea5909db16edd359a279d619b3fed42fe34f58931ae512",
          "sha256": "383a626211a60397705f9fe9a9453efcff7b9e115a7d7dbb247a17970f98ffd8",
          "sha1": "a593917108d97673b800b5f2386627171d6c0bf9",
          "md5": "eaf3cded43604fcb637b154b74a981ea"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bravepipeproject",
          "module": "timeago-parser",
          "version": {
            "requires": "v0.24.8-2.3.4"
          }
        },
        {
          "group": "com.github.TeamNewPipe",
          "module": "nanojson",
          "version": {
            "requires": "e9d656ddb49a412a5a0a5d5ef20ca7ef09549996"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.1"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "4.31.1"
          }
        },
        {
          "group": "org.mozilla",
          "module": "rhino",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.mozilla",
          "module": "rhino-engine",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.github.evermind-zz",
          "module": "hlsdownloader",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-runtime",
          "version": {
            "requires": "4.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "extractor-v0.24.8-2.3.4.jar",
          "url": "extractor-v0.24.8-2.3.4.jar",
          "size": 973423,
          "sha512": "22346c82c8d0486b8d2cbfd8a5a4f2e04e01e0a339b9eb73f6af83809cc793f35f75c8156d59b830d5ea5909db16edd359a279d619b3fed42fe34f58931ae512",
          "sha256": "383a626211a60397705f9fe9a9453efcff7b9e115a7d7dbb247a17970f98ffd8",
          "sha1": "a593917108d97673b800b5f2386627171d6c0bf9",
          "md5": "eaf3cded43604fcb637b154b74a981ea"
        }
      ]
    }
  ]
}
