{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bravepipeproject",
    "module": "extractor",
    "version": "v0.24.8-2.3.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.wire",
          "module": "wire-runtime",
          "version": {
            "requires": "4.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "extractor-v0.24.8-2.3.3.jar",
          "url": "extractor-v0.24.8-2.3.3.jar",
          "size": 961131,
          "sha512": "564dc251f1dc346b6816daef978fdb0591093fef346f0c3b4db07e0596ef0c402939e8b81bba3a528658ffbb3f9aba6f85760687c4fbd407236496e871a66b19",
          "sha256": "60e1282a47eb101c7f0f965c53a2d8a413c8406a5c01a64e99458c2d1e09ca17",
          "sha1": "102254d8f6e9f4e3f076a4fc155145834cbbb145",
          "md5": "1ee89135cd360f97467045df81509383"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bravepipeproject",
          "module": "timeago-parser",
          "version": {
            "requires": "v0.24.8-2.3.3"
          }
        },
        {
          "group": "com.github.TeamNewPipe",
          "module": "nanojson",
          "version": {
            "requires": "e9d656ddb49a412a5a0a5d5ef20ca7ef09549996"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.1"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "4.31.1"
          }
        },
        {
          "group": "org.mozilla",
          "module": "rhino",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.mozilla",
          "module": "rhino-engine",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.github.evermind-zz",
          "module": "hlsdownloader",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-runtime",
          "version": {
            "requires": "4.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "extractor-v0.24.8-2.3.3.jar",
          "url": "extractor-v0.24.8-2.3.3.jar",
          "size": 961131,
          "sha512": "564dc251f1dc346b6816daef978fdb0591093fef346f0c3b4db07e0596ef0c402939e8b81bba3a528658ffbb3f9aba6f85760687c4fbd407236496e871a66b19",
          "sha256": "60e1282a47eb101c7f0f965c53a2d8a413c8406a5c01a64e99458c2d1e09ca17",
          "sha1": "102254d8f6e9f4e3f076a4fc155145834cbbb145",
          "md5": "1ee89135cd360f97467045df81509383"
        }
      ]
    }
  ]
}
