{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bravepipeproject",
    "module": "timeago-generator",
    "version": "v0.24.8-2.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "timeago-generator-v0.24.8-2.3.0.jar",
          "url": "timeago-generator-v0.24.8-2.3.0.jar",
          "size": 13011,
          "sha512": "c87575ee0a36f5031a377bd34bd6f1f30447ee14b168ffcfc533b7f9d02f6094b879769ee4d34569ddee37db00b9218d7ac694a96173a5fa2b377943a5d24359",
          "sha256": "ecb9158317fdbf12a27264d23079c08677992a0adf2d3bc91baf64db2fd960d2",
          "sha1": "8cf4c6ee6844dce06723ca9cd9557e990a9d6716",
          "md5": "baaaa600e972222cd208630d8d48cc64"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.TeamNewPipe",
          "module": "nanojson",
          "version": {
            "requires": "e9d656ddb49a412a5a0a5d5ef20ca7ef09549996"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.github.bravepipeproject",
          "module": "timeago-parser",
          "version": {
            "requires": "v0.24.8-2.3.0"
          }
        }
      ],
      "files": [
        {
          "name": "timeago-generator-v0.24.8-2.3.0.jar",
          "url": "timeago-generator-v0.24.8-2.3.0.jar",
          "size": 13011,
          "sha512": "c87575ee0a36f5031a377bd34bd6f1f30447ee14b168ffcfc533b7f9d02f6094b879769ee4d34569ddee37db00b9218d7ac694a96173a5fa2b377943a5d24359",
          "sha256": "ecb9158317fdbf12a27264d23079c08677992a0adf2d3bc91baf64db2fd960d2",
          "sha1": "8cf4c6ee6844dce06723ca9cd9557e990a9d6716",
          "md5": "baaaa600e972222cd208630d8d48cc64"
        }
      ]
    }
  ]
}
