{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.bravepipeproject",
    "module": "extractor",
    "version": "v0.24.8-2.2.8",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.9"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.squareup.wire",
          "module": "wire-runtime",
          "version": {
            "requires": "4.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "extractor-v0.24.8-2.2.8.jar",
          "url": "extractor-v0.24.8-2.2.8.jar",
          "size": 983015,
          "sha512": "e49f31658560ed4f806edd71a4941e602c8f92b064ed2cf0052d188311deaa553cbf6484cd44bb5ca307cd0e60a771fd4a6de340fc08b750d24d2cd651b0f693",
          "sha256": "e0c24a766da72aca59812217d1706aaca5adc835c95e1890d5ea9246c8326c24",
          "sha1": "bf8a85e1abb41b0fbab71e35008eec6b94067eef",
          "md5": "01d3177f5503e2bcda07855be6266077"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 11,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.github.bravepipeproject",
          "module": "timeago-parser",
          "version": {
            "requires": "v0.24.8-2.2.8"
          }
        },
        {
          "group": "com.github.TeamNewPipe",
          "module": "nanojson",
          "version": {
            "requires": "e9d656ddb49a412a5a0a5d5ef20ca7ef09549996"
          }
        },
        {
          "group": "org.jsoup",
          "module": "jsoup",
          "version": {
            "requires": "1.21.1"
          }
        },
        {
          "group": "com.google.code.findbugs",
          "module": "jsr305",
          "version": {
            "requires": "3.0.2"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "4.31.1"
          }
        },
        {
          "group": "org.mozilla",
          "module": "rhino",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "org.mozilla",
          "module": "rhino-engine",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.squareup.wire",
          "module": "wire-runtime",
          "version": {
            "requires": "4.5.2"
          }
        }
      ],
      "files": [
        {
          "name": "extractor-v0.24.8-2.2.8.jar",
          "url": "extractor-v0.24.8-2.2.8.jar",
          "size": 983015,
          "sha512": "e49f31658560ed4f806edd71a4941e602c8f92b064ed2cf0052d188311deaa553cbf6484cd44bb5ca307cd0e60a771fd4a6de340fc08b750d24d2cd651b0f693",
          "sha256": "e0c24a766da72aca59812217d1706aaca5adc835c95e1890d5ea9246c8326c24",
          "sha1": "bf8a85e1abb41b0fbab71e35008eec6b94067eef",
          "md5": "01d3177f5503e2bcda07855be6266077"
        }
      ]
    }
  ]
}
